services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "api.sls.fi:172.16.2.136"
      - "granska-api.sls.fi:172.16.2.136"
      - "testa-vonwright.sls.fi:172.16.2.136"
    image: docker.io/slsfinland/digital-edition-frontend-ng:latest
    ports:
      - 8080:4201
