services:
  nginx:
    image: docker.io/library/nginx:1.25.3
    depends_on:
      - web
    ports:
      - ${PORT}:80
    restart: unless-stopped
    volumes:
      - browser-static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE}
    restart: unless-stopped
    volumes:
      - browser-static:/digital-edition-frontend-ng/dist/app/browser
volumes:
  browser-static:
